### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by baimafeima** [kpdyer/fteproxy#183]
What is the current development status of fteproxy? Is it still maintained? If yes, could you release a newer version here on GitHub? If not, what alternatives can you recommend?

**Comment by kpdyer** [comment]
It's still maintained. However, there aren't any features in the pipeline.

Is there a missing feature that you'd like to request?

**Comment by leggewie** [comment]
I'm not the requester of this ticket, but for me #160 would be a high prio request.  The package is otherwise at risk of being dropped fairly soon.

**Comment by kpdyer** [comment]
Understood, thanks Rolf. I'll updated #160 with any progress.
