### ISSUE TITLE
"brew install wget" on VirtualBox Hackintosh results in "Illegal instruction: 4"

### ISSUE THREAD

**Issue by kpdyer** [kpdyer/fteproxy#64]
By default, wget does not work on hackintosh.

```
$ brew install wget
...
[Install completes successfully.]
$ wget http://google.com/
Illegal instruction: 4
```

Whereas, it should download the google.com homepage and shouldn't result in an illegal instruction.

**Comment by HenkPoley** [comment]
Just for people googling for fixing 'Illegal instruction: 4' with Homebrew/brew and dropping by. This is now defined in: /usr/local/Homebrew/Library/Homebrew/extend/ENV/std.rb

e.g.: `sed -i -e 's/march=nehalem/march=core2/g' /usr/local/Homebrew/Library/Homebrew/extend/ENV/std.rb`

**Comment by Tizioincognit0** [comment]
I have the same problem.
> Updates to homebrew moved where -march is defined to /usr/local/Library/Homebrew/extend/ENV/super.rb. The new command is:
> sudo sed -i -e 's/march=native/march=core2/g' /usr/local/Library/Homebrew/extend/ENV/super.rb

I tried this but it says “No such file or directory”.
